# Location Information
location:
  name: OASI Weather Station
  country: Brazil
  state: Pernambuco
  city: Itacuruba
  region: Nordeste

LATITUDE: -8.79225
LONGITUDE: -38.68853
ALTITUDE: 390

# Dashboard Configuration
TIME_OPTIONS:
  Ultima Hora: 60
  Ultimas 2 horas: 120
  Ultimas 6 horas: 360
  Ultimas 12 horas: 720
  Ultimas dia: 1440
  Ultimas 2 dias: 2880

UPDATE_INTERVAL_SECONDS: 10


# Server Configuration
SERVER_HOST: "0.0.0.0"
SERVER_PORT: 8051

# Weather Station Configuration
WEATHER_STATION_CONFIG: "sigma.yaml"
ALLSKY_CAMERA_CONFIG: "oculus.yaml"

# Database Configuration
DATABASE_PATH_PATTERN: "weather_data_{year}.db"  # Creates separate file per year
DATABASE_SAVE_INTERVAL_SECONDS: 600  # Save to database every 10 minutes

#